development:
  adapter: postgresql
  encoding: unicode
  database: bank_test
  host: localhost
  pool: 5
  username: taka
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: bank_rspec
  host: localhost
  pool: 5
  username: taka
  password: root