development:
  adapter: postgresql
  encoding: unicode
  database: bank_test
  host: localhost
  pool: 5
  username: taka
  password: root

<<<<<<< Updated upstream
test:
=======
production:
  adapter: postgresql
  database: bank_production
  username: root
  password: root


production:
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000