development:
  adapter: postgresql
  encoding: unicode
  database: bank_test
  host: localhost
  pool: 5
  username: taka
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: bank_rspec
  host: localhost
  pool: 5
  username: taka
  password: root

production:
  adapter: postgresql
  database: your_production_db
  username: your_production_username
  password: your_production_pass